[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist" # Change this to your Vue.js build output directory
  command = "vue-cli-service build" # Change this to your build command
